# Generated by Django 4.1.3 on 2022-11-07 16:29

from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Заголовок')),
                ('desc', models.CharField(max_length=10000, verbose_name='Опис')),
                ('link_video', models.URLField(blank=True, verbose_name='Посилання на відео')),
                ('photo', models.ImageField(upload_to=main_page.models.All_Inform.get_file_name, verbose_name='Фото')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Відображення')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Про ресторан',
                'verbose_name_plural': 'Про ресторан',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Назва заходу')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вартість')),
                ('desc', models.CharField(blank=True, max_length=1000, verbose_name='Опис')),
                ('image', models.ImageField(upload_to=main_page.models.Event.get_file_name, verbose_name='Титульне фото')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата/час початку')),
            ],
            options={
                'verbose_name': 'Захід',
                'verbose_name_plural': 'Заходи',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія меню', 'verbose_name_plural': 'Категорії меню'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Відо  браження'),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Позиція відображення'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='desc',
            field=models.TextField(blank=True, max_length=500, verbose_name='Опис страви'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.CharField(max_length=150, verbose_name='Склад страви'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Входить до спеціальної пропозиції'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Вдображення'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.Dish.get_file_name, verbose_name='Фото страви'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Назва страви'),
        ),
    ]
