# Generated by Django 4.1.3 on 2022-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_gallery_alter_all_inform_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=50, verbose_name='місто')),
                ('location', models.CharField(max_length=250, verbose_name='адреса')),
                ('post_index', models.PositiveSmallIntegerField(max_length=8, verbose_name='поштовий індекс')),
                ('open_days_start', models.CharField(max_length=15, verbose_name='перший робочий день')),
                ('open_days_end', models.CharField(max_length=15, verbose_name='останній робочий день')),
                ('open_hours_start', models.TimeField(verbose_name='початок робочого дня')),
                ('open_hours_end', models.TimeField(verbose_name='кінець робочого дня')),
                ('e_mail_1', models.EmailField(max_length=254, verbose_name='перший E_mail')),
                ('e_mail_2', models.EmailField(blank=True, default='', max_length=254, verbose_name='другий E_mail')),
                ('call_1', models.SmallIntegerField(max_length=12, verbose_name='номер телефона')),
                ('call_2', models.SmallIntegerField(blank=True, default=True, max_length=12, verbose_name='номер телефона')),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('skype', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'загальна інформація ресторану',
                'verbose_name_plural': 'загальна інформація ресторану',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('pk',), 'verbose_name': 'галерея', 'verbose_name_plural': 'галерея'},
        ),
    ]
