# Generated by Django 4.1.3 on 2022-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_informationrestaurant_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationrestaurant',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='активне'),
        ),
        migrations.AlterField(
            model_name='informationrestaurant',
            name='call_1',
            field=models.TextField(max_length=15, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='informationrestaurant',
            name='call_2',
            field=models.TextField(blank=True, default=True, max_length=15, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='informationrestaurant',
            name='post_index',
            field=models.TextField(max_length=15, verbose_name='поштовий індекс'),
        ),
    ]
