# Generated by Django 4.1.3 on 2022-11-10 23:23

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_personal_alter_informationrestaurant_call_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name="ім'я")),
                ('surname', models.CharField(max_length=25, verbose_name='Прізвище')),
                ('major', models.CharField(max_length=30, verbose_name='Посада')),
                ('desc', models.TextField(max_length=1000, verbose_name='Відгук')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Відображення')),
                ('photo', models.ImageField(upload_to=main_page.models.Testimonials.get_file_name, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
