# Generated by Django 4.1.3 on 2022-11-11 00:19

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Заголовок')),
                ('desc', models.TextField(max_length=300, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to=main_page.models.HeroSection.get_file_name, verbose_name='Фото')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Відображення')),
            ],
            options={
                'verbose_name': 'слайди у шапці',
                'verbose_name_plural': 'слайди у шапці',
            },
        ),
    ]
