# Generated by Django 4.1.3 on 2022-11-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_herosection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_inform',
            old_name='desc',
            new_name='description',
        ),
    ]
