# Generated by Django 4.1.3 on 2022-11-14 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Невірний формат Email', regex='^[^W_]\\w+-?\\w+@[a-z]+(\\.[a-zA-Z0-9]+)*$')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Невірний формат номеру телефона', regex='^380\\d{2}( -)?\\d{7}$')])),
                ('date_order', models.DateField()),
                ('time_order', models.TimeField()),
                ('persons', models.PositiveSmallIntegerField()),
                ('massage', models.TextField(max_length=1000)),
                ('is_processing', models.BooleanField(default=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_in',),
            },
        ),
    ]
