# Generated by Django 4.1.3 on 2022-11-14 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='date_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='останнє опрацювання'),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='date_order',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Невірний формат Email', regex='^[^W_]\\w+-?\\w+@[a-z]+(\\.[a-zA-Z0-9]+)*$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='is_processing',
            field=models.BooleanField(default=False, verbose_name='Опрацьованно'),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='massage',
            field=models.TextField(max_length=1000, verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='persons',
            field=models.PositiveSmallIntegerField(verbose_name='кількість людей'),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Невірний формат номеру телефона', regex='^380\\d{2}( -)?\\d{7}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='time_order',
            field=models.TimeField(verbose_name='час'),
        ),
    ]
