# Generated by Django 4.1.3 on 2022-11-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_userreservation_date_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreservation',
            options={'ordering': ('-date_in',), 'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
    ]
