# Generated by Django 4.1.3 on 2022-11-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_userreservation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreservation',
            old_name='massage',
            new_name='message',
        ),
    ]
