# Generated by Django 4.1.3 on 2022-11-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_massage_userreservation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreservation',
            old_name='date_order',
            new_name='date_reserve',
        ),
        migrations.RenameField(
            model_name='userreservation',
            old_name='time_order',
            new_name='time_reserve',
        ),
    ]
